# -*- coding: utf-8 -*-
"""Final_Assignment_Part2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xuy1Uci5V4mzKY5hdZ9rFKdHNGg7o0qc
"""

!pip install dash plotly pandas

import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd

# Sample Data
data = {'Month': ['Jan','Feb','Mar','Apr','May'],
        'Sales': [200, 250, 300, 400, 350]}
df = pd.DataFrame(data)

# Dash App
app = dash.Dash(__name__)

# Layout
app.layout = html.Div([
    html.H1("Sales Dashboard - Plotly + Dash", style={'textAlign': 'center'}),

    dcc.Graph(
        id='line-graph',
        figure=px.line(df, x='Month', y='Sales', title='Monthly Sales Line Chart')
    ),

    dcc.Graph(
        id='bar-graph',
        figure=px.bar(df, x='Month', y='Sales', title='Monthly Sales Bar Chart')
    )
])

# Run App
if __name__ == '__main__':
    app.run(debug=True)